version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: isahc
    versions:
    - 1.0.3
    - 1.1.0
    - 1.2.0
    - 1.3.0
